### ISSUE TITLE
Post Aggregation - not working

### ISSUE THREAD

**Issue by Shabhana** [7eggs/node-druid-query#32]
Below is the Nodejs code snippet using Druid :

var Druid = require('druid-query')
  , Client = Druid.Client
  , Query = Druid.Query
  , client = new Client('http://10.10.2.1')

var q5 = client.groupBy()
q5.dataSource('stmp_dlv_1')
q5.granularity('month')
q5.dimensions(['txn_mth'])
q5.aggregation('doubleSum', 'GROSS', 'sum_gross')
q5.postAggregation('arithmetic', 'sum_gross', '/', [
  Query.postAggregation('fieldAccess', 'GROSS' , 'sum_gross'),
  Query.postAggregation('fieldAccess', 'NBC' , 'sum_nbc')
])
q5.interval(Date.UTC(2019, 0, 1), Date.UTC(2019, 1, 0))

q5.exec(function(err, result) {
  if (err) {
    // handle error...
    console.log("*****error*****",err)
  }
  else {
    console.log("******result****",result);
  }
})

It is prefectly working without post Aggregation, but getting below error on adding Post Aggregation.

*****error***** Error: Unknown error (status: %d) while executing query: %j
    at Request.onresponse [as _callback] (/Users/srajathii/Documents/hikma/Site/node_modules/druid-query/lib/client.js:225:16)
    at Request.self.callback (/Users/srajathii/Documents/hikma/Site/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/srajathii/Documents/hikma/Site/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/srajathii/Documents/hikma/Site/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

Can you please help with this

**Comment by netik** [comment]
Same goes for floatMax, no support there either.

I think this library is largely incomplete and doesn't support features in the latest druid (0.20)

**Comment by netik** [comment]
fwiw, I ended up abandoning this library and moving over to Ply and using druidRequestor outside of Ply for JSON queries, which returns promises. It seems to be far more supported.
