### ISSUE TITLE
Unknown error (status: %d) while executing query: %s

### ISSUE THREAD

**Issue by SanjayMindinventory** [7eggs/node-druid-query#39]
Error: Unknown error (status: %d) while executing query: %s
    at Request.onresponse [as _callback] (/home/sanjay/Work/Projects/curvecue-infrastructure/webapi/node_modules/druid-query/lib/client.js:226:16)
    at Request.self.callback (/home/sanjay/Work/Projects/curvecue-infrastructure/webapi/node_modules/request/request.js:186:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:486:12)
    at Request.<anonymous> (/home/sanjay/Work/Projects/curvecue-infrastructure/webapi/node_modules/request/request.js:1060:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:486:12)
    at IncomingMessage.<anonymous> (/home/sanjay/Work/Projects/curvecue-infrastructure/webapi/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22) undefined

**Comment by SanjayMindinventory** [comment]
This is the Query i'm trying 

let client = new Client('http://127.0.0.1:8888')

client
    .groupBy()
    .dataSource('rfq')
    .granularity('month')
    .dimensions('isin', 'rfqQty')
    .aggregation('doubleSum', 'rfqQty', 'sumRfqQty')
    .intervals(new Date('2021-01-04T00:00:00.00'), new Date('2021-01-08T00:00:00.000'))
    .exec((result) => {
      console.log('result', result)
    })

**Comment by jainishan2323** [comment]
@SanjayMindinventory  did you found any solution for this. Facing same issue.
